// <auto-generated />
using System;
using Market.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Market.Infrastructure.Migrations
{
    [DbContext(typeof(MarketDbContext))]
    [Migration("20260330113246_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Market.Domain.Entities.AssetTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("FromTraderId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_trader_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("SellOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sell_order_id");

                    b.Property<Guid?>("ToTraderId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_trader_id");

                    b.Property<Guid?>("TradeId")
                        .HasColumnType("uuid")
                        .HasColumnName("trade_id");

                    b.HasKey("Id")
                        .HasName("pk_asset_transfers");

                    b.HasIndex("TradeId")
                        .HasDatabaseName("ix_asset_transfers_trade_id")
                        .HasFilter("trade_id IS NOT NULL");

                    b.HasIndex("AssetTypeId", "CreatedAt")
                        .HasDatabaseName("ix_asset_transfers_asset_created");

                    b.ToTable("asset_transfers", (string)null);
                });

            modelBuilder.Entity("Market.Domain.Entities.AssetType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_asset_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_types_code");

                    b.ToTable("asset_types", (string)null);
                });

            modelBuilder.Entity("Market.Domain.Entities.CreditTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("FromTraderId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_trader_id");

                    b.Property<Guid?>("ToTraderId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_trader_id");

                    b.Property<Guid?>("TradeId")
                        .HasColumnType("uuid")
                        .HasColumnName("trade_id");

                    b.HasKey("Id")
                        .HasName("pk_credit_transfers");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_credit_transfers_created");

                    b.HasIndex("TradeId")
                        .HasDatabaseName("ix_credit_transfers_trade_id")
                        .HasFilter("trade_id IS NOT NULL");

                    b.ToTable("credit_transfers", (string)null);
                });

            modelBuilder.Entity("Market.Domain.Entities.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssetTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("CreditDelta")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("credit_delta");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entry_type");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<decimal?>("QuantityDelta")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity_delta");

                    b.Property<Guid?>("SellOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sell_order_id");

                    b.Property<Guid?>("TradeId")
                        .HasColumnType("uuid")
                        .HasColumnName("trade_id");

                    b.Property<Guid>("TraderId")
                        .HasColumnType("uuid")
                        .HasColumnName("trader_id");

                    b.HasKey("Id")
                        .HasName("pk_ledger_entries");

                    b.HasIndex("SellOrderId")
                        .HasDatabaseName("ix_ledger_sell_order_id")
                        .HasFilter("sell_order_id IS NOT NULL");

                    b.HasIndex("TradeId")
                        .HasDatabaseName("ix_ledger_trade_id")
                        .HasFilter("trade_id IS NOT NULL");

                    b.HasIndex("TraderId", "CreatedAt")
                        .HasDatabaseName("ix_ledger_trader_created");

                    b.ToTable("ledger_entries", (string)null);
                });

            modelBuilder.Entity("Market.Domain.Entities.SellOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("OriginalQuantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("original_quantity");

                    b.Property<decimal>("RemainingQuantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("remaining_quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TraderId")
                        .HasColumnType("uuid")
                        .HasColumnName("trader_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sell_orders");

                    b.HasIndex("TraderId")
                        .HasDatabaseName("ix_sell_orders_trader_id");

                    b.HasIndex("AssetTypeId", "Status", "UnitPrice", "CreatedAt")
                        .HasDatabaseName("ix_sell_orders_asset_status_price_created");

                    b.ToTable("sell_orders", (string)null);
                });

            modelBuilder.Entity("Market.Domain.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_type_id");

                    b.Property<decimal>("AverageUnitPrice")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("average_unit_price");

                    b.Property<Guid>("BuyerTraderId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_trader_id");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<decimal>("RequestedQuantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("requested_quantity");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_cost");

                    b.Property<decimal>("TotalQuantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("total_quantity");

                    b.HasKey("Id")
                        .HasName("pk_trades");

                    b.HasIndex("AssetTypeId")
                        .HasDatabaseName("ix_trades_asset_type_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_trades_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("BuyerTraderId", "ExecutedAt")
                        .HasDatabaseName("ix_trades_buyer_executed");

                    b.ToTable("trades", (string)null);
                });

            modelBuilder.Entity("Market.Domain.Entities.TradeFill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_type_id");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SellOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sell_order_id");

                    b.Property<Guid>("SellerTraderId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_trader_id");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("sub_total");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("uuid")
                        .HasColumnName("trade_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_trade_fills");

                    b.HasIndex("SellOrderId")
                        .HasDatabaseName("ix_trade_fills_sell_order_id");

                    b.HasIndex("TradeId")
                        .HasDatabaseName("ix_trade_fills_trade_id");

                    b.HasIndex("AssetTypeId", "ExecutedAt")
                        .HasDatabaseName("ix_trade_fills_asset_executed");

                    b.ToTable("trade_fills", (string)null);
                });

            modelBuilder.Entity("Market.Domain.Entities.Trader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_traders");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_traders_name");

                    b.ToTable("traders", (string)null);
                });

            modelBuilder.Entity("Market.Domain.Entities.TraderAssetBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_type_id");

                    b.Property<decimal>("ReservedQuantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("reserved_quantity");

                    b.Property<decimal>("TotalQuantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("total_quantity");

                    b.Property<Guid>("TraderId")
                        .HasColumnType("uuid")
                        .HasColumnName("trader_id");

                    b.HasKey("Id")
                        .HasName("pk_trader_asset_balances");

                    b.HasIndex("AssetTypeId")
                        .HasDatabaseName("ix_trader_asset_balances_asset_type_id");

                    b.HasIndex("TraderId", "AssetTypeId")
                        .IsUnique()
                        .HasDatabaseName("ix_trader_asset_balances_trader_asset");

                    b.ToTable("trader_asset_balances", (string)null);
                });

            modelBuilder.Entity("Market.Domain.Entities.TraderCreditBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Credits")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("credits");

                    b.Property<Guid>("TraderId")
                        .HasColumnType("uuid")
                        .HasColumnName("trader_id");

                    b.HasKey("Id")
                        .HasName("pk_trader_credit_balances");

                    b.HasIndex("TraderId")
                        .IsUnique()
                        .HasDatabaseName("ix_trader_credit_balances_trader_id");

                    b.ToTable("trader_credit_balances", (string)null);
                });

            modelBuilder.Entity("Market.Domain.Entities.SellOrder", b =>
                {
                    b.HasOne("Market.Domain.Entities.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sell_orders_asset_types_asset_type_id");

                    b.HasOne("Market.Domain.Entities.Trader", "Trader")
                        .WithMany("SellOrders")
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sell_orders_traders_trader_id");

                    b.Navigation("AssetType");

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("Market.Domain.Entities.Trade", b =>
                {
                    b.HasOne("Market.Domain.Entities.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trades_asset_types_asset_type_id");

                    b.HasOne("Market.Domain.Entities.Trader", "BuyerTrader")
                        .WithMany()
                        .HasForeignKey("BuyerTraderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trades_traders_buyer_trader_id");

                    b.Navigation("AssetType");

                    b.Navigation("BuyerTrader");
                });

            modelBuilder.Entity("Market.Domain.Entities.TradeFill", b =>
                {
                    b.HasOne("Market.Domain.Entities.SellOrder", "SellOrder")
                        .WithMany("Fills")
                        .HasForeignKey("SellOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trade_fills_sell_orders_sell_order_id");

                    b.HasOne("Market.Domain.Entities.Trade", "Trade")
                        .WithMany("Fills")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trade_fills_trades_trade_id");

                    b.Navigation("SellOrder");

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("Market.Domain.Entities.TraderAssetBalance", b =>
                {
                    b.HasOne("Market.Domain.Entities.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trader_asset_balances_asset_types_asset_type_id");

                    b.HasOne("Market.Domain.Entities.Trader", "Trader")
                        .WithMany("AssetBalances")
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trader_asset_balances_traders_trader_id");

                    b.Navigation("AssetType");

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("Market.Domain.Entities.TraderCreditBalance", b =>
                {
                    b.HasOne("Market.Domain.Entities.Trader", "Trader")
                        .WithOne("CreditBalance")
                        .HasForeignKey("Market.Domain.Entities.TraderCreditBalance", "TraderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trader_credit_balances_traders_trader_id");

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("Market.Domain.Entities.SellOrder", b =>
                {
                    b.Navigation("Fills");
                });

            modelBuilder.Entity("Market.Domain.Entities.Trade", b =>
                {
                    b.Navigation("Fills");
                });

            modelBuilder.Entity("Market.Domain.Entities.Trader", b =>
                {
                    b.Navigation("AssetBalances");

                    b.Navigation("CreditBalance");

                    b.Navigation("SellOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
